networks:
  app_net:
    driver: bridge

services:
  postgres:
    image: pgvector/pgvector:pg16 # Uses an image with pgvector pre-installed
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-agent_service}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_net

  db-migrator:
    build:
      context: .
      dockerfile: docker/Dockerfile.db_migrator
    env_file:
      - .env
      - docker.env # Overwrites POSTGRES_HOST and POSTGRES_PORT
    depends_on:
      postgres:
        condition: service_healthy # Wait for postgres to be ready
    networks:
      - app_net

  agent_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    ports:
      - "8080:8080"
    env_file:
      - .env
      - docker.env # Overwrites POSTGRES_HOST and POSTGRES_PORT
    depends_on:
      db-migrator:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/info"]
      interval: 5s
      timeout: 5s
      retries: 5
    # Volume mount of development-only credentials since compose watch doesn't sync ignored files and doesn't do initial sync when the service starts
    volumes:
      - ./privatecredentials:/privatecredentials
    develop:
      watch:
        - path: src/agents/
          action: sync+restart
          target: /app/agents/
        - path: src/schema/
          action: sync+restart
          target: /app/schema/
        - path: src/service/
          action: sync+restart
          target: /app/service/
        - path: src/core/
          action: sync+restart
          target: /app/core/
        - path: src/memory/
          action: sync+restart
          target: /app/memory/
    networks:
      - app_net

  streamlit_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - agent_service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
      - docker.env # Overwrites POSTGRES_HOST and POSTGRES_PORT
    environment:
      - AGENT_URL=http://agent_service:8080
    develop:
      watch:
        - path: src/client/
          action: sync+restart
          target: /app/client/
        - path: src/schema/
          action: sync+restart
          target: /app/schema/
        - path: src/streamlit_app.py
          action: sync+restart
          target: /app/streamlit_app.py
    networks:
      - app_net

  cv_preprocess:
    build:
      context: .
      dockerfile: docker/Dockerfile.cv_preprocess
    env_file:
      - .env
      - docker.env # Overwrites POSTGRES_HOST and POSTGRES_PORT
    depends_on:
      db-migrator:
        condition: service_completed_successfully
      ollama:
        condition: service_healthy # Wait for Ollama
    volumes:
      - ./data:/app/data # Mounts host 'data' folder into the container
    networks:
      - app_net

  cv_process:
    build:
      context: .
      dockerfile: docker/Dockerfile.cv_process
    env_file:
      - .env
      - docker.env # Overwrites POSTGRES_HOST and POSTGRES_PORT
    # Keep STDIN open for interaction
    stdin_open: true
    # Allocate a pseudo-TTY
    tty: true
    depends_on:
      db-migrator:
        condition: service_completed_successfully
      ollama:
        condition: service_healthy # Wait for Ollama
    volumes:
      - ./data:/app/data # Mounts host 'data' folder into the container
    networks:
      - app_net

  fake_data:
    build:
      context: .
      dockerfile: docker/Dockerfile.fake_data
    env_file:
      - .env
      - docker.env # Overwrites POSTGRES_HOST and POSTGRES_PORT
    environment:
      - PYTHONPATH=/app
    # Keep STDIN open for interaction
    stdin_open: true
    # Allocate a pseudo-TTY
    tty: true
    volumes:
      - ./data:/app/data # Mounts host 'data' folder into the container
    depends_on:
      ollama:
        condition: service_healthy # Wait for Ollama
    networks:
      - app_net

  ollama:
    image: ollama/ollama
    restart: always
    volumes:
      - ollama_data:/root/.ollama # Persists models
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_net

volumes:
  postgres_data:
  ollama_data:
