"""Initial schema from models

Revision ID: 891975947c23
Revises: 
Create Date: 2025-10-07 19:59:13.348938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '891975947c23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_suitability_automatic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Text(), nullable=False),
    sa.Column('position_number', sa.Text(), nullable=True),
    sa.Column('suitability_automatic', sa.Text(), nullable=True),
    sa.Column('suitability_automatic_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', 'application_id'),
    schema='cv'
    )
    op.create_index(op.f('ix_cv_applicant_suitability_automatic_position_number'), 'applicant_suitability_automatic', ['position_number'], unique=False, schema='cv')
    op.create_table('applicant_suitability_automatic_experiment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Text(), nullable=False),
    sa.Column('position_number', sa.Text(), nullable=True),
    sa.Column('suitability_automatic', sa.Text(), nullable=True),
    sa.Column('suitability_automatic_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experiment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'application_id'),
    schema='cv'
    )
    op.create_index(op.f('ix_cv_applicant_suitability_automatic_experiment_position_number'), 'applicant_suitability_automatic_experiment', ['position_number'], unique=False, schema='cv')
    op.create_table('applicant_suitability_manual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Text(), nullable=False),
    sa.Column('position_number', sa.Text(), nullable=True),
    sa.Column('suitability_manual', sa.Text(), nullable=True),
    sa.Column('suitability_comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'application_id'),
    schema='cv'
    )
    op.create_index(op.f('ix_cv_applicant_suitability_manual_position_number'), 'applicant_suitability_manual', ['position_number'], unique=False, schema='cv')
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Text(), nullable=False),
    sa.Column('position_number', sa.Text(), nullable=True),
    sa.Column('atsi_identity', sa.Text(), nullable=True),
    sa.Column('disability_status', sa.Text(), nullable=True),
    sa.Column('age_range', sa.Text(), nullable=True),
    sa.Column('gender_identity', sa.Text(), nullable=True),
    sa.Column('lgbtqia_community', sa.Text(), nullable=True),
    sa.Column('carer_responsibilities', sa.Text(), nullable=True),
    sa.Column('speaks_language_other_than_english', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'application_id'),
    schema='cv'
    )
    op.create_index(op.f('ix_cv_applicants_position_number'), 'applicants', ['position_number'], unique=False, schema='cv')
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_number', sa.Text(), nullable=False),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'position_number'),
    schema='cv'
    )
    op.create_index(op.f('ix_cv_positions_position_number'), 'positions', ['position_number'], unique=False, schema='cv')
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_index(op.f('ix_cv_positions_position_number'), table_name='positions', schema='cv')
    op.drop_table('positions', schema='cv')
    op.drop_index(op.f('ix_cv_applicants_position_number'), table_name='applicants', schema='cv')
    op.drop_table('applicants', schema='cv')
    op.drop_index(op.f('ix_cv_applicant_suitability_manual_position_number'), table_name='applicant_suitability_manual', schema='cv')
    op.drop_table('applicant_suitability_manual', schema='cv')
    op.drop_index(op.f('ix_cv_applicant_suitability_automatic_experiment_position_number'), table_name='applicant_suitability_automatic_experiment', schema='cv')
    op.drop_table('applicant_suitability_automatic_experiment', schema='cv')
    op.drop_index(op.f('ix_cv_applicant_suitability_automatic_position_number'), table_name='applicant_suitability_automatic', schema='cv')
    op.drop_table('applicant_suitability_automatic', schema='cv')
    # ### end Alembic commands ###
