"""update positions table column names

Revision ID: a47e955df4ec
Revises: 891975947c23
Create Date: 2025-10-07 22:23:31.286847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47e955df4ec'
down_revision: Union[str, Sequence[str], None] = '891975947c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('department', sa.Text(), nullable=True), schema='cv')
    op.add_column('positions', sa.Column('level', sa.Text(), nullable=True), schema='cv')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'level', schema='cv')
    op.drop_column('positions', 'department', schema='cv')
    # ### end Alembic commands ###
